// Lightweight view of the question bank (generated by scripts/gen-manifest.mjs).
// Importing this does NOT pull question content into the bundle — only counts.
// Use this on the dashboard so the home page stays small as the bank grows.

import data from "@/generated/manifest.json";

export interface Manifest {
  total: number;
  subtopics: Record<string, { category: string; count: number }>;
}

export const MANIFEST = data as Manifest;

export function countFor(subtopic: string): number {
  return MANIFEST.subtopics[subtopic]?.count ?? 0;
}
